[package]
name = "ledger-tui"
version = "0.1.0"
edition = "2021"
authors = ["mertwole"]

[dependencies]
futures = "0.3.30"
ledger_bitcoin_client = "0.4.1"
ledger-lib = "0.1.0"
ledger-proto = "0.1.0"
log = "0.4.22"
pretty_env_logger = "0.5.0"
ratatui = "0.27.0"
tokio = "1.38.0"
