[package]
name = "ledger-tui"
version = "0.1.0"
edition = "2021"
authors = ["mertwole"]

[dependencies]
binance_spot_connector_rust = "1.1.0"
bs58 = "0.5.1"
futures = "0.3.30"
ledger_bitcoin_client = "0.4.1"
ledger-lib = "0.1.0"
ledger-proto = "0.1.0"
log = "0.4.22"
pretty_env_logger = "0.5.0"
qrcode = "0.14.1"
ratatui = "0.27.0"
rust_decimal = "1.35.0"
rust_decimal_macros = "1.35.0"
serde = "1.0.204"
serde_json = "1.0.120"
tokio = "1.38.0"
tui-widget-list = "0.10.0"
