[package]
name = "input-mapping-derive"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
input-mapping-common.workspace = true

itertools.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
